name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-22.04    
    # Define job steps
    steps:
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Check-out repository
      uses: actions/checkout@v2
    
    - name: Install poetry
      uses: snok/install-poetry@v1
    
    - name: Install package
      run: poetry install
    
    - name: Test with pytest
      run: poetry run pytest tests/ --cov=word_text_counter --cov-branch --cov-report xml --verbose
    
    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml # coverage report

    - name: Build documentation
      run: poetry run make clean html --directory docs/

